import '../rules/rules_builder.dart';
import 'tkcms_rules.dart';

/// Options of the festenao rule presets.
class FestenaoRulesOptions {
  /// Add `<parent>/user_access/{userId}` (app level user rights, readable by
  /// their owner, server written).
  final bool userAccess;

  /// Add the `access user self` rules (a user gets and deletes its own access
  /// document).
  final bool accessSelf;

  /// Add the public read flag
  /// (`<parent>/access/{entity}/entity_id/{entityId}/public_access/public`):
  /// when it says `read: true` anyone, signed out included, reads the entity
  /// and its subtree. The flag itself is readable by anyone and only ever
  /// written by the api function.
  final bool publicAccess;

  /// Deepest entity level generated (1: projects under an app, 2: entities
  /// under a project...). Every level from 1 to [maxDepth] gets the same rule
  /// sets.
  final int maxDepth;

  /// Header comment of the generated file.
  final String? header;

  /// Creates preset options.
  const FestenaoRulesOptions({
    this.userAccess = false,
    this.accessSelf = false,
    this.publicAccess = false,
    this.maxDepth = 1,
    this.header,
  });
}

FirestoreRules _newRules(FestenaoRulesOptions options, String defaultHeader) {
  var rules = FirestoreRules();
  rules.headerComment(options.header ?? defaultHeader);
  return rules;
}

/// The api context rules (`festenao_firebase_api_context`): a cloud
/// function owns every access mutation, clients read their entities, write
/// their data and their private area.
///
/// Sub entity (`/{top}/{topId}/{entity}/{entityId}`) rules only: the entity
/// document (members read, admins write) and its `data/**` (members read,
/// writers write), invites readable, access managed by admins, own access
/// rows readable, per user private data — and, with
/// [FestenaoRulesOptions.publicAccess], the api written public read flag.
///
/// The entity itself is never created by a client: the api does, which is
/// what makes this the preset of an app whose entities are created through
/// its api (a playelio playlist, a notelio booklet).
FirestoreRules festenaoApiContextRules({
  FestenaoRulesOptions options = const FestenaoRulesOptions(),
}) {
  var rules = _newRules(
    options,
    'festenao api context: the api function owns every mutation of access,\n'
    'clients read their entities, write their data and their private area.\n'
    'Generated by festenao_firebase, do not edit.',
  );
  var tkCms = TkCmsFirestoreRules(rules: rules, denyAll: true);
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    level.addEntityRules();
    level.addInviteReadRules();
    level.addAccessManageRules();
    level.addAccessUserReadRules();
    if (options.accessSelf) {
      level.addAccessSelfRules();
    }
    if (options.publicAccess) {
      level.addPublicAccessRules(adminWrite: false);
    }
    level.addUserPrvRules();
    if (options.userAccess) {
      level.addUserAccessRules();
    }
  }
  return rules;
}

/// The no-api context rules (`festenao_firebase_no_api_context`): no
/// backend, the client creates its entities and their access documents
/// itself (`creatorUserId`), plus public read flags and public get.
FirestoreRules festenaoNoApiContextRules({
  FestenaoRulesOptions options = const FestenaoRulesOptions(),
}) {
  var rules = _newRules(
    options,
    'festenao no api context: no backend, the client creates its entities and\n'
    'their access documents itself (creatorUserId), public read flags.\n'
    'Generated by festenao_firebase, do not edit.',
  );
  var tkCms = TkCmsFirestoreRules(rules: rules, denyAll: true);
  rules.blankLine();
  tkCms.level(0).addPublicGetRules();
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    level.addEntityRules();
    level.addInviteReadRules();
    level.addAccessManageRules();
    level.addAccessUserReadRules();
    if (options.accessSelf) {
      level.addAccessSelfRules();
    }
    level.addCreatorRules();
    level.addPublicAccessRules(scope: TkCmsPublicReadScope.dataOnly);
    level.addUserPrvRules();
    if (options.userAccess) {
      level.addUserAccessRules();
    }
  }
  return rules;
}

/// The full api context rules (`festenao_firebase_full_api_context`): top
/// level entities (`/{entity}/{entityId}`) and sub entities, standalone
/// invites by code at both levels, public read flags, per user private data.
FirestoreRules festenaoFullApiContextRules({
  FestenaoRulesOptions options = const FestenaoRulesOptions(),
}) {
  var rules = _newRules(
    options,
    'festenao full api context: top level and sub entities, standalone\n'
    'invites by code, public read flags, per user private data.\n'
    'Generated by festenao_firebase, do not edit.',
  );
  var tkCms = TkCmsFirestoreRules(rules: rules);
  rules.blankLine();
  tkCms.level(0).addPublicGetRules();
  tkCms.level(1).addPublicGetRules();

  // Top level entities (app): standalone invites, legacy whole entity rule.
  var top = tkCms.level(0);
  rules.blankLine();
  rules.comment('\nTop (Example: app/<app_id>)\n');
  top.addStandaloneInviteRules();
  top.addInviteReadRules();
  top.addEntityRules(
    dataScope: TkCmsEntityDataScope.all,
    allReadAccess: tkCmsRulesWriteAccess,
  );
  top.addAccessUserReadRules(legacy: true);

  // Sub entities (project).
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    rules.blankLine();
    rules.comment('\nSub (Example: app/<app_id>/project/<project_id>)\n');
    level.addStandaloneInviteRules();
    level.addEntityRules();
    level.addInviteReadRules();
    level.addAccessManageRules();
    level.addAccessUserReadRules();
    if (options.accessSelf) {
      level.addAccessSelfRules();
    }
  }

  top.addPublicAccessRules();
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    tkCms.level(depth).addPublicAccessRules();
  }
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    level.addUserPrvRules();
    if (options.userAccess) {
      level.addUserAccessRules();
    }
  }
  return rules;
}

/// The server rules of an app with a full api (calendelio style): the api
/// function owns every mutation of access, top level and sub entities are
/// readable by their members and publicly when flagged, no client side
/// invites nor public flag writes, per user private data and app level user
/// rights.
FirestoreRules festenaoServerFullApiRules({
  FestenaoRulesOptions options = const FestenaoRulesOptions(userAccess: true),
}) {
  var rules = _newRules(
    options,
    'festenao full api server rules: entities, access, invites, public flag,\n'
    'per user private data, the api function owning every mutation of access.\n'
    'Generated by festenao_firebase, do not edit.',
  );
  var tkCms = TkCmsFirestoreRules(rules: rules);
  rules.blankLine();
  tkCms.level(0).addPublicGetRules();
  tkCms.level(1).addPublicGetRules();

  var top = tkCms.level(0);
  rules.blankLine();
  rules.comment('\nTop (Example: app/<app_id>) - Cloud functions supported\n');
  top.addInviteReadRules();
  top.addEntityRules(
    dataScope: TkCmsEntityDataScope.all,
    allReadAccess: tkCmsRulesWriteAccess,
  );
  top.addAccessUserReadRules(legacy: true);

  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    rules.blankLine();
    rules.comment(
      '\nSub (Example: app/<app_id>/<entity>/<entity_id>) - Cloud functions supported\n',
    );
    level.addEntityRules();
    level.addInviteReadRules();
    level.addAccessManageRules();
    level.addAccessUserReadRules();
    if (options.accessSelf) {
      level.addAccessSelfRules();
    }
  }

  top.addPublicAccessRules(adminWrite: false);
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    tkCms.level(depth).addPublicAccessRules(adminWrite: false);
  }
  for (var depth = 1; depth <= options.maxDepth; depth++) {
    var level = tkCms.level(depth);
    level.addUserPrvRules();
    if (options.userAccess) {
      level.addUserAccessRules();
    }
  }
  return rules;
}

/// The legacy `festenao_dartff/firestore.rules` shape: top level and sub
/// entities with whole entity rules, standalone invites, per user private
/// document at the app and entity levels, public read flags.
FirestoreRules festenaoDartffRules({
  FestenaoRulesOptions options = const FestenaoRulesOptions(),
}) {
  var rules = _newRules(
    options,
    'festenao_dartff rules: top level and sub entities, standalone invites,\n'
    'per user private data, public read flags.\n'
    'Generated by festenao_firebase, do not edit.',
  );
  var tkCms = TkCmsFirestoreRules(rules: rules);
  rules.blankLine();
  tkCms.level(1).addPublicGetRules();
  tkCms.level(0).addPublicGetRules();

  var top = tkCms.level(0);
  rules.blankLine();
  rules.comment('\nTop (Example: app/<app_id>)\n');
  top.addStandaloneInviteRules();
  top.addInviteReadRules();
  top.addEntityRules(
    dataScope: TkCmsEntityDataScope.all,
    allReadAccess: tkCmsRulesWriteAccess,
  );
  top.addAccessUserReadRules(legacy: true);

  var sub = tkCms.level(1);
  rules.blankLine();
  rules.comment('\nSub\n');
  sub.addStandaloneInviteRules();
  sub.addEntityRules(dataScope: TkCmsEntityDataScope.all);
  sub.addInviteReadRules();
  sub.addAccessUserReadRules(legacy: true);

  sub.addUserPrvRules();
  sub.addEntityUserPrvRules();

  top.addPublicAccessRules();
  sub.addPublicAccessRules();
  return rules;
}

/// The presets by name, as used by the generation tool.
final festenaoRulesPresets = <String, FirestoreRules Function()>{
  'api_context': festenaoApiContextRules,
  'no_api_context': festenaoNoApiContextRules,
  'full_api_context': festenaoFullApiContextRules,
  'server_full_api': festenaoServerFullApiRules,
  'dartff': festenaoDartffRules,
};
