name: _
publish_to: none
environment:
  sdk: ^3.7.0
workspace:
  - packages/festenao_blur_hash
  - packages/festenao_common
  - packages/festenao_support
  - packages_flutter/festenao_admin_base_app
  - packages_flutter/festenao_audio_player
  - packages_flutter/festenao_base_app
  - packages_flutter/festenao_firebase_flutter
  - packages_flutter/festenao_theme
  - packages_flutter/festenao_icon
  - packages_flutter/festenao_icon/example

