name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/festenao_blur_hash
  - packages/festenao_common
  - packages/festenao_support
  - packages_flutter/festenao_admin_base_app
  - packages_flutter/festenao_audio_player
  - packages_flutter/festenao_base_app
  - packages_flutter/festenao_firebase_flutter
  - packages_flutter/festenao_theme
  - packages_flutter/festenao_icon
  - packages_flutter/festenao_icon/example
  - packages_flutter/festenao_markdown
  - packages_flutter/festenao_common_flutter
  - packages_flutter/festenao_youtube_player
  - packages_flutter/festenao_youtube_player/example/fyp_example
  - packages_flutter/festenao_lyrics_player
  - packages_flutter/festenao_lyrics_player/example/flp_example
  - packages_flutter/festenao_media_base_app
  - packages_flutter/festenao_google_auth

