name: festenao_firebase_flutter
description: "Firebase (auth, firestore, storage)"
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tekartik_firebase_auth_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: auth_flutter
  tekartik_firebase_firestore_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: firestore_flutter
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: firebase_flutter
  tekaly_assets:
    git:
      url: https://github.com/tekartikprj/tekaly.git
      ref: dart3a
      path: packages/tekaly_assets
  tekartik_firebase_flutter_ui_auth:
    git:
      url: https://github.com/tekartik/firebase_ui.dart
      ref: dart3a
      path: packages/firebase_flutter_ui_auth
  tekartik_firebase_storage_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: storage_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
resolution: workspace

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
