name: festenao_support
description: Festenao support tools
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  fs_shim: ">=2.3.3+1"
  tkcms_support:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      ref: dart3a
      path: packages/tkcms_support
  festenao_common:
    git:
      url: https://github.com/tekaly/festenao
      ref: dart3a
      path: packages/festenao_common
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      ref: dart3a
      path: packages/tkcms_common
  dev_build: ">=1.1.2"


dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

resolution: workspace
