name: festenao_support
description: Festenao support tools
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.0"
  sembast: ">=3.7.4+3"
  fs_shim: ">=2.3.3+1"
  tkcms_support:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_support
  festenao_common:
    git:
      url: https://github.com/tekaly/festenao
      path: packages/festenao_common
  tkcms_common:
    git:
      url: https://github.com/tekartikprj/tkcms.git
      path: packages/tkcms_common
  dev_build: ">=1.1.2"
  tekartik_prj_tktools:
    git:
      url: https://github.com/tekartikprj/tktools.git
      path: packages/prj_tktools
  tekartik_build_menu_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/build_menu_flutter
  tekartik_app_dev_menu:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      path: app_dev_menu
  tekartik_firebase_build_menu_flutter:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/firebase_build_menu_flutter
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/firebase_build
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
  tekaly_sembast_synced:
    git:
      url: https://github.com/tekartikprj/tekaly
      path: packages/sembast_synced

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

resolution: workspace
